apiVersion: v1
kind: Service
metadata:
  name: openobserve
  namespace: openobserve
spec:
  clusterIP: None
  selector:
    app: openobserve
  ports:
    - name: http
      port: 5080
      targetPort: 5080

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: openobserve
  namespace: openobserve
  labels:
    name: openobserve
spec:
  serviceName: openobserve
  replicas: 1
  selector:
    matchLabels:
      name: openobserve
      app: openobserve
  template:
    metadata:
      labels:
        name: openobserve
        app: openobserve
    spec:
      # 对于本地来说，权限这里可以注释掉
      #      securityContext:
      #        fsGroup: 2000
      #        runAsUser: 10000
      #        runAsGroup: 3000
      #        runAsNonRoot: true
      initContainers:
        - name: fix-permissions
          image: busybox:1.36
          command: [ "sh", "-c", "mkdir -p /data/cache && chown -R 10000:3000 /data" ]
      containers:
        - name: openobserve
          image: public.ecr.aws/zinclabs/openobserve:v0.90.3
          env:
            - name: ZO_ROOT_USER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: openobserve-auth
                  key: email
            - name: ZO_ROOT_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openobserve-auth
                  key: password
            - name: ZO_DATA_DIR
              value: /data
            - name: ZO_LOCAL_MODE
              value: "true"
            - name: ZO_HTTP_ADDR
              value: "0.0.0.0"
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "4"
              memory: "8Gi"
            requests:
              cpu: "1"
              memory: "2Gi"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5080
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 20
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5080
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 20
            failureThreshold: 3
          # 优雅关闭
          lifecycle:
            preStop:
              exec:
                command: [ "/bin/sh", "-c", "sleep 10" ]
          ports:
            - containerPort: 5080
              name: http
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
#        storageClassName: hostpath   # Docker Desktop 可用，对于云来说建议配置实际的sc，例如:aws对应的gp3模版
        resources:
          requests:
            storage: 50Gi # 本地可以50gb
